//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rickar
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasEstudiante
    {
        public int IdNota { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Labouno { get; set; }
        public Nullable<int> Labodos { get; set; }
        public Nullable<int> Labotres { get; set; }
        public Nullable<int> parcialuno { get; set; }
        public Nullable<int> parcialdos { get; set; }
        public Nullable<int> parcialtres { get; set; }
    }
}
